name: Hello World Workflow

# Définir le trigger : se déclenche lors d'un push
on:
  push:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest  # Serveur Ubuntu

    steps:
      # Étape 1 : Checkout du repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Étape 2 : Afficher "Hello world !"
      - name: Print Hello World
        run: echo "Hello world !"
