name: Merge PR

on:
  pull_request:
    types: closed

jobs:
  notification_merge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: "Notifier le merge de la PR"
        run: echo "La PR a été mergée avec succès !"















# name: 3.2 - Merge PR Workflow Définit le nom du workflow qui apparaîtra dans l'interface de GitHub.

# on: Indique que ce qui suit définit les événements qui déclencheront ce workflow.


# pull_request: Spécifie que le workflow doit réagir aux événements liés aux Pull Requests.

# types: [closed] Filtre pour que le workflow ne se lance que lorsqu'une Pull Request est fermée (qu'elle soit fusionnée ou non).

# jobs: Déclare la liste des travaux (jobs) à exécuter.

# notify_on_merge: Donne un identifiant unique à ce job.

# runs-on: ubuntu-latest Indique que ce job doit s'exécuter sur un serveur virtuel fourni par GitHub utilisant la dernière version d'Ubuntu.

# if: github.event.pull_request.merged == true Ajoute une condition : ce job ne s'exécutera que si la Pull Request qui a déclenché le workflow a été fusionnée (merged).